version: '3.6'
services:
  app:
    container_name: socrates-app
    build:
      context: ./src/app
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
  redis:
    container_name: socrates-redis
    image: redis:3.2-alpine
    ports: 
      - "9379:6379"
    volumes:
      - redis_data:/data
  postgres:
    container_name: socrates-postgres
    image: postgres:9.6-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9432:5432"
    volumes:
      - psqldata:/var/lib/pgsql/9.6/data
      - psqlupgrade:/var/lib/pgsql/upgrade

volumes:
  redis_data:
  psqldata:
  psqlupgrade: