version: '3.6'
services:
  # app:
  #   container_name: socrates-app
  #   build:
  #     context: ./src/app
  #   depends_on:
  #     - redis
  #     - postgres
  #     - flyway
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #   ports:
  #     - "5000:5000"
  plato:
    container_name: plato-app
    build:
      context: ./src/plato
    environment: 
      DB_NAME: knowledge
      DB_USER: shinalee
      DB_PASSWORD: therapist2009
      DB_HOST: localhost
      DB_PORT: 5432
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "j@v0q-t9@0rmje=^5+v8*#=7r$$(jz!3jji6^la1ogb%)!(1=u"
    # command: python /code/app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
      - postgres
      - flyway
    environment:
      - DEBUG=True 
    ports:
      - "8000:8000"
    networks:
      - nginx_network      
  plato-nginx:
    restart: always
    container_name: plato-nginx
    build: 
      context: ./src/nginx
    ports:
      - "8080:80"
    depends_on:
      - plato
    networks: 
      - nginx_network
  redis:
    container_name: socrates-redis
    image: redis:3.2-alpine
    ports: 
      - "9379:6379"
    volumes:
      - redis_data:/data
  postgres:
    container_name: socrates-postgres
    build:
      context: ./src/db
    environment: 
      FILLA_DB_USER: shinalee
      FILLA_DB_PASSWORD: therapist2009
      FILLA_DB_DATABASE: knowledge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9432:5432"
    volumes:
      - psqldata:/var/lib/pgsql/9.6/data
      - psqlupgrade:/var/lib/pgsql/upgrade
  flyway:
    container_name: socrates-flyway
    command: -url=jdbc:postgresql://postgres:5432/knowledge -user=shinalee -password=therapist2009 -connectRetries=60 migrate
    build:
      context: ./src/flyway
    volumes:
      - .:/flyway/sql
    depends_on:
      - postgres
    
networks:
  nginx_network:
    driver: bridge

volumes:
  redis_data:
  psqldata:
  psqlupgrade: