version: '3.6'
services:
  app:
    container_name: socrates-app
    build:
      context: ./src/app
    depends_on:
      - redis
      - postgres
      - flyway
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"
  redis:
    container_name: socrates-redis
    image: redis:3.2-alpine
    ports: 
      - "9379:6379"
    volumes:
      - redis_data:/data
  postgres:
    container_name: socrates-postgres
    build:
      context: ./src/db
    environment: 
      FILLA_DB_USER: shinalee
      FILLA_DB_PASSWORD: therapist2009
      FILLA_DB_DATABASE: knowledge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9432:5432"
    volumes:
      - psqldata:/var/lib/pgsql/9.6/data
      - psqlupgrade:/var/lib/pgsql/upgrade
  flyway:
    container_name: socrates-flyway
    command: -url=jdbc:postgresql://postgres:5432/knowledge -user=shinalee -password=therapist2009 -connectRetries=60 migrate
    build:
      context: ./src/flyway
    volumes:
      - .:/flyway/sql
    depends_on:
      - postgres

volumes:
  redis_data:
  psqldata:
  psqlupgrade: